import os
import io
import uuid
import json
import pytest
from PIL import Image

from fastapi.testclient import TestClient
from sqlalchemy.orm import Session

from app.db.models.document import Document
from app.db.models.page import Page
from app.db.models.ocr import OCRPageResult
from app.domain.enums import DocumentStatus, PageStatus
from app.storage.factory import get_storage_provider
from app.ocr.registry import get_ocr_engine

# We use a static multi-frame TIFF generated by a script to avoid Pillow/pytest runtime state bugs
def get_multiframe_tiff():
    import os
    path = os.path.join("tests", "assets", "multiframe.tiff")
    with open(path, "rb") as f:
        return f.read()

# Need a fake multi-page PDF. We can use reportlab or fpdf, or try PyMuPDF. 
# We'll use PyMuPDF if available.
def create_multipage_pdf():
    try:
        import fitz
    except ImportError:
        pytest.skip("PyMuPDF not installed, skipping PDF e2e test.")
        return b""
        
    doc = fitz.open()
    page1 = doc.new_page(width=100, height=100)
    page1.insert_text(fitz.Point(10, 10), "Page 1 Text", fontsize=12)
    
    page2 = doc.new_page(width=100, height=100)
    page2.insert_text(fitz.Point(10, 10), "Page 2 Text", fontsize=12)
    
    out = doc.write()
    doc.close()
    return out

class TestIntegrationE2E:
    def test_e2e_multipage_pdf(self, client, test_org, db_session, monkeypatch):
        # We need fake OCR engine for deterministic test if paddle isn't installed.
        # But wait, user says: "If PaddleOCR is installed, use it for one integration test."
        # We will try to load paddle, if not we monkeypatch.
        paddle_installed = True
        try:
            import paddle
        except ImportError:
            paddle_installed = False
            
        if not paddle_installed:
            from tests.fakes.fake_ocr_engine import FakeOCREngine
            fake_engine = FakeOCREngine()
            monkeypatch.setattr("app.core.config.Config.OCR_PROVIDER", "fake", raising=False)
            monkeypatch.setattr("app.ocr.registry._create_engine", lambda p: fake_engine)

        pdf_bytes = create_multipage_pdf()
        
        # 1. Create Claim
        claim_res = client.post("/api/v1/claims", json={"title": "E2E PDF Claim"}, headers={"X-Organization-ID": str(test_org.id)})
        assert claim_res.status_code == 201
        claim_id = claim_res.json()["id"]
        
        # 2. Upload Document (Phase 2)
        files = {"file": ("test.pdf", pdf_bytes, "application/pdf")}
        upload_res = client.post(f"/api/v1/claims/{claim_id}/documents/upload", files=files, headers={"X-Organization-ID": str(test_org.id)})
        assert upload_res.status_code == 201
        doc_id = upload_res.json()["document"]["id"]
        
        # 3. Verify Phase 2 DB state
        doc = db_session.query(Document).filter(Document.id == doc_id).first()
        assert doc.status == DocumentStatus.UPLOADED
        assert doc.size_bytes == len(pdf_bytes)
        
        # 4. Trigger Conversion (Phase 3)
        # Note: the standard API might not have a standalone convert endpoint, 
        # or maybe it's /api/v1/documents/{doc_id}/convert?
        # Let's check router.
        # Actually, let's call the OCR endpoint which runs OCR, but wait, OCR endpoint assumes conversion is already done?
        # Or does OCR endpoint orchestrate both? Let's check `ocr_service.py` or the router.
        
        # In this project, Phase 3 and Phase 4 might be triggered differently. 
        # Let's trigger conversion service directly if there's no endpoint.
        db_session.expire_all()
        from app.services.conversion_service import ConversionService
        from app.storage.factory import get_storage_provider
        
        storage = get_storage_provider()
        conv_svc = ConversionService(db_session, storage)
        
        pages = conv_svc.convert_document(test_org.id, uuid.UUID(doc_id))
        assert len(pages) == 2
        
        db_session.refresh(doc)
        assert doc.status == DocumentStatus.CONVERTED
        assert doc.page_count == 2
        
        # 5. Verify PNG artifacts exist
        for p in pages:
            assert storage.exists(p.storage_key)
            assert p.status == PageStatus.MATERIALIZED
            
        # 6. Trigger OCR (Phase 4)
        ocr_res = client.post(f"/api/v1/documents/{doc_id}/ocr", headers={"X-Organization-ID": str(test_org.id)})
        assert ocr_res.status_code == 200
        
        db_session.refresh(doc)
        assert doc.status == DocumentStatus.OCR_COMPLETED
        
        # 7. Verify OCR records
        from app.db.models.ocr import OCRPageResult, OCRRegion
        for p in pages:
            db_session.refresh(p)
            assert p.status == PageStatus.OCR_COMPLETED
            ocr_results = db_session.query(OCRPageResult).filter(OCRPageResult.page_id == p.id).all()
            assert len(ocr_results) == 1
            res = ocr_results[0]
            assert storage.exists(res.artifact_storage_key)
            
            # Read JSON artifact
            artifact_bytes = storage.open(res.artifact_storage_key).read()
            artifact = json.loads(artifact_bytes.decode("utf-8"))
            assert artifact["schema_version"] == "1.0"
            assert artifact["page_number"] == p.page_number
            
            regions = db_session.query(OCRRegion).filter(OCRRegion.ocr_result_id == res.id).all()
            assert len(regions) > 0 or not paddle_installed # fake OCR always produces regions, Paddle might produce none if empty, but we wrote text.
            
        # 8. Trigger Classification (Phase 5)
        classify_res = client.post(f"/api/v1/documents/{doc_id}/classify", headers={"X-Organization-ID": str(test_org.id)})
        assert classify_res.status_code == 200
        classify_data = classify_res.json()
        
        assert classify_data["document_id"] == doc_id
        assert "document_type" in classify_data
        
        db_session.refresh(doc)
        assert doc.status == DocumentStatus.CLASSIFIED
        assert doc.document_type == classify_data["document_type"]
        
        # Verify JSON artifact
        from app.db.models.classification import DocumentClassification
        db_class = db_session.query(DocumentClassification).filter(DocumentClassification.document_id == doc.id).first()
        assert db_class is not None
        assert storage.exists(db_class.artifact_storage_key)
        
        # 9. GET Classification
        get_class_res = client.get(f"/api/v1/documents/{doc_id}/classification", headers={"X-Organization-ID": str(test_org.id)})
        assert get_class_res.status_code == 200
        assert get_class_res.json()["document_type"] == classify_data["document_type"]

        # 10. Trigger Extraction (Phase 6)
        extract_res = client.post(f"/api/v1/documents/{doc_id}/extract", headers={"X-Organization-ID": str(test_org.id)})
        assert extract_res.status_code == 200
        extract_data = extract_res.json()
        assert extract_data["document_id"] == doc_id
        assert extract_data["status"] == "COMPLETED"
        assert extract_data["schema_name"] == f"{classify_data['document_type']}_extraction"
        
        db_session.refresh(doc)
        assert doc.status == DocumentStatus.EXTRACTED
        
        # Verify JSON artifact
        from app.db.models.extraction import ExtractionRun
        db_ext = db_session.query(ExtractionRun).filter(ExtractionRun.document_id == doc.id).first()
        assert db_ext is not None
        assert storage.exists(db_ext.artifact_storage_key)
        
        # 11. GET Extraction
        get_ext_res = client.get(f"/api/v1/documents/{doc_id}/extraction", headers={"X-Organization-ID": str(test_org.id)})
        assert get_ext_res.status_code == 200
        assert get_ext_res.json()["id"] == str(db_ext.id)
    def test_e2e_multiframe_tiff(self, client, test_org, db_session, monkeypatch):
        import logging
        logging.getLogger("PIL").setLevel(logging.INFO)
        logging.getLogger("PIL.TiffImagePlugin").setLevel(logging.INFO)

        paddle_installed = True
        try:
            import paddle
        except ImportError:
            paddle_installed = False
            
        if not paddle_installed:
            from tests.fakes.fake_ocr_engine import FakeOCREngine
            fake_engine = FakeOCREngine()
            monkeypatch.setattr("app.core.config.Config.OCR_PROVIDER", "fake", raising=False)
            monkeypatch.setattr("app.ocr.registry._create_engine", lambda p: fake_engine)

        tiff_bytes = get_multiframe_tiff()
        
        # 1. Create Claim
        claim_res = client.post("/api/v1/claims", json={"title": "E2E TIFF Claim"}, headers={"X-Organization-ID": str(test_org.id)})
        assert claim_res.status_code == 201
        claim_id = claim_res.json()["id"]
        
        # 2. Upload Document
        files = {"file": ("test.tiff", tiff_bytes, "image/tiff")}
        upload_res = client.post(f"/api/v1/claims/{claim_id}/documents/upload", files=files, headers={"X-Organization-ID": str(test_org.id)})
        assert upload_res.status_code == 201
        doc_id = upload_res.json()["document"]["id"]
        
        # 3. Trigger Conversion
        db_session.expire_all()
        from app.services.conversion_service import ConversionService
        from app.storage.factory import get_storage_provider
        
        storage = get_storage_provider()
        conv_svc = ConversionService(db_session, storage)
        
        pages = conv_svc.convert_document(test_org.id, uuid.UUID(doc_id))
        assert len(pages) == 2
        
        # 4. Trigger OCR
        ocr_res = client.post(f"/api/v1/documents/{doc_id}/ocr", headers={"X-Organization-ID": str(test_org.id)})
        assert ocr_res.status_code == 200
