"""Add provider metadata to ExtractionRun

Revision ID: 06a3ae7fecf6
Revises: b2becf4bc7fd
Create Date: 2026-07-24 20:38:16.887404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a3ae7fecf6'
down_revision: Union[str, Sequence[str], None] = 'b2becf4bc7fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_runs', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('extraction_runs', sa.Column('model', sa.String(length=100), nullable=True))
    op.add_column('extraction_runs', sa.Column('provider_version', sa.String(length=50), nullable=True))
    op.add_column('extraction_runs', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.add_column('extraction_runs', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('extraction_runs', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('extraction_runs', sa.Column('request_id', sa.String(length=255), nullable=True))
    op.add_column('extraction_runs', sa.Column('finish_reason', sa.String(length=50), nullable=True))
    op.add_column('extraction_runs', sa.Column('cached', sa.Boolean(), nullable=True))
    op.add_column('extraction_runs', sa.Column('prompt_version', sa.String(length=50), nullable=True))
    op.add_column('extraction_runs', sa.Column('provider_input_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_runs', 'provider_input_hash')
    op.drop_column('extraction_runs', 'prompt_version')
    op.drop_column('extraction_runs', 'cached')
    op.drop_column('extraction_runs', 'finish_reason')
    op.drop_column('extraction_runs', 'request_id')
    op.drop_column('extraction_runs', 'completion_tokens')
    op.drop_column('extraction_runs', 'prompt_tokens')
    op.drop_column('extraction_runs', 'latency_ms')
    op.drop_column('extraction_runs', 'provider_version')
    op.drop_column('extraction_runs', 'model')
    op.drop_column('extraction_runs', 'provider')
    # ### end Alembic commands ###
