"""add_extraction_models

Revision ID: 203f39413e09
Revises: be65e84efa81
Create Date: 2026-07-24 19:38:03.132942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '203f39413e09'
down_revision: Union[str, Sequence[str], None] = 'be65e84efa81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('classification_id', sa.Uuid(), nullable=False),
    sa.Column('extractor_name', sa.String(length=50), nullable=False),
    sa.Column('extractor_version', sa.String(length=50), nullable=False),
    sa.Column('schema_name', sa.String(length=50), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='extractionstatus'), nullable=False),
    sa.Column('artifact_storage_key', sa.String(length=1024), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['classification_id'], ['document_classifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_runs_classification_id'), 'extraction_runs', ['classification_id'], unique=False)
    op.create_index(op.f('ix_extraction_runs_document_id'), 'extraction_runs', ['document_id'], unique=True)
    op.create_index(op.f('ix_extraction_runs_organization_id'), 'extraction_runs', ['organization_id'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('extraction_run_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('raw_value', sa.String(), nullable=True),
    sa.Column('normalized_value', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_fields_extraction_run_id'), 'extracted_fields', ['extraction_run_id'], unique=False)
    op.create_table('field_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('extracted_field_id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=True),
    sa.Column('ocr_region_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extracted_field_id'], ['extracted_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ocr_region_id'], ['ocr_regions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_evidence_extracted_field_id'), 'field_evidence', ['extracted_field_id'], unique=False)
    bind = op.get_bind()
    if bind.engine.name != 'sqlite':
        op.alter_column('documents', 'status',
                   existing_type=sa.VARCHAR(length=10),
                   type_=sa.Enum('REGISTERED', 'UPLOADED', 'CONVERTING', 'CONVERTED', 'CONVERSION_FAILED', 'PROCESSING', 'PROCESSED', 'FAILED', 'ARCHIVED', 'OCR_PROCESSING', 'OCR_COMPLETED', 'OCR_PARTIAL', 'OCR_FAILED', 'CLASSIFICATION_PROCESSING', 'CLASSIFIED', 'CLASSIFICATION_FAILED', 'EXTRACTION_PROCESSING', 'EXTRACTED', 'EXTRACTION_FAILED', name='documentstatus'),
                   existing_nullable=False)
        op.alter_column('pages', 'status',
                   existing_type=sa.VARCHAR(length=10),
                   type_=sa.Enum('PENDING', 'MATERIALIZED', 'PROCESSING', 'PROCESSED', 'FAILED', 'OCR_PROCESSING', 'OCR_COMPLETED', 'OCR_FAILED', name='pagestatus'),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.engine.name != 'sqlite':
        op.alter_column('pages', 'status',
                   existing_type=sa.Enum('PENDING', 'MATERIALIZED', 'PROCESSING', 'PROCESSED', 'FAILED', 'OCR_PROCESSING', 'OCR_COMPLETED', 'OCR_FAILED', name='pagestatus'),
                   type_=sa.VARCHAR(length=10),
                   existing_nullable=False)
        op.alter_column('documents', 'status',
                   existing_type=sa.Enum('REGISTERED', 'UPLOADED', 'CONVERTING', 'CONVERTED', 'CONVERSION_FAILED', 'PROCESSING', 'PROCESSED', 'FAILED', 'ARCHIVED', 'OCR_PROCESSING', 'OCR_COMPLETED', 'OCR_PARTIAL', 'OCR_FAILED', 'CLASSIFICATION_PROCESSING', 'CLASSIFIED', 'CLASSIFICATION_FAILED', 'EXTRACTION_PROCESSING', 'EXTRACTED', 'EXTRACTION_FAILED', name='documentstatus'),
                   type_=sa.VARCHAR(length=10),
                   existing_nullable=False)
    op.drop_index(op.f('ix_field_evidence_extracted_field_id'), table_name='field_evidence')
    op.drop_table('field_evidence')
    op.drop_index(op.f('ix_extracted_fields_extraction_run_id'), table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index(op.f('ix_extraction_runs_organization_id'), table_name='extraction_runs')
    op.drop_index(op.f('ix_extraction_runs_document_id'), table_name='extraction_runs')
    op.drop_index(op.f('ix_extraction_runs_classification_id'), table_name='extraction_runs')
    op.drop_table('extraction_runs')
    # ### end Alembic commands ###
