"""Add OCR models

Revision ID: 50cbdf71ecd3
Revises: d0e7b298584e
Create Date: 2026-07-22 20:15:24.337670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50cbdf71ecd3'
down_revision: Union[str, Sequence[str], None] = 'd0e7b298584e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_page_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('engine_version', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('full_text', sa.String(), nullable=False),
    sa.Column('region_count', sa.Integer(), nullable=False),
    sa.Column('average_confidence', sa.Float(), nullable=False),
    sa.Column('processing_time_ms', sa.Float(), nullable=False),
    sa.Column('artifact_storage_key', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_page_results_page_id'), 'ocr_page_results', ['page_id'], unique=True)
    op.create_table('ocr_regions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ocr_result_id', sa.Uuid(), nullable=False),
    sa.Column('region_index', sa.Integer(), nullable=False),
    sa.Column('reading_order', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.Column('x2', sa.Float(), nullable=False),
    sa.Column('y2', sa.Float(), nullable=False),
    sa.Column('polygon_json', sa.String(), nullable=True),
    sa.Column('region_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ocr_result_id'], ['ocr_page_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ocr_result_id', 'reading_order', name='uq_ocr_reading_order'),
    sa.UniqueConstraint('ocr_result_id', 'region_index', name='uq_ocr_region_index')
    )
    op.create_index(op.f('ix_ocr_regions_ocr_result_id'), 'ocr_regions', ['ocr_result_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_ocr_regions_ocr_result_id'), table_name='ocr_regions')
    op.drop_table('ocr_regions')
    op.drop_index(op.f('ix_ocr_page_results_page_id'), table_name='ocr_page_results')
    op.drop_table('ocr_page_results')
    # ### end Alembic commands ###
