"""phase13_analytics

Revision ID: 94abb85820fe
Revises: fffaaad336f9
Create Date: 2026-07-25 11:29:55.578791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94abb85820fe'
down_revision: Union[str, Sequence[str], None] = 'fffaaad336f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_daily_statistics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('documents_processed', sa.Integer(), nullable=True),
    sa.Column('pages_processed', sa.Integer(), nullable=True),
    sa.Column('ocr_success_count', sa.Integer(), nullable=True),
    sa.Column('ocr_failure_count', sa.Integer(), nullable=True),
    sa.Column('extraction_success_count', sa.Integer(), nullable=True),
    sa.Column('validation_failure_count', sa.Integer(), nullable=True),
    sa.Column('review_required_count', sa.Integer(), nullable=True),
    sa.Column('auto_approved_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('analytics_historical_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_historical_metrics_name_time', 'analytics_historical_metrics', ['metric_name', 'timestamp'], unique=False)
    op.create_table('analytics_provider_statistics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('requests_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('circuit_breaker_openings', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_stats_date_name', 'analytics_provider_statistics', ['date', 'provider_name'], unique=True)
    op.create_table('analytics_sla_statistics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('p50_latency_ms', sa.Float(), nullable=True),
    sa.Column('p90_latency_ms', sa.Float(), nullable=True),
    sa.Column('p95_latency_ms', sa.Float(), nullable=True),
    sa.Column('p99_latency_ms', sa.Float(), nullable=True),
    sa.Column('job_success_rate', sa.Float(), nullable=True),
    sa.Column('pipeline_success_rate', sa.Float(), nullable=True),
    sa.Column('avg_queue_wait_ms', sa.Float(), nullable=True),
    sa.Column('avg_processing_time_ms', sa.Float(), nullable=True),
    sa.Column('worker_utilization_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('analytics_cost_statistics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cost_stats_date_org_provider', 'analytics_cost_statistics', ['date', 'organization_id', 'provider_name'], unique=True)
    op.create_table('analytics_organization_statistics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_documents', sa.Integer(), nullable=True),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('storage_used_bytes', sa.Integer(), nullable=True),
    sa.Column('active_users', sa.Integer(), nullable=True),
    sa.Column('jobs_processed', sa.Integer(), nullable=True),
    sa.Column('reviews_completed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_org_stats_org_date', 'analytics_organization_statistics', ['organization_id', 'date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_org_stats_org_date', table_name='analytics_organization_statistics')
    op.drop_table('analytics_organization_statistics')
    op.drop_index('ix_cost_stats_date_org_provider', table_name='analytics_cost_statistics')
    op.drop_table('analytics_cost_statistics')
    op.drop_table('analytics_sla_statistics')
    op.drop_index('ix_provider_stats_date_name', table_name='analytics_provider_statistics')
    op.drop_table('analytics_provider_statistics')
    op.drop_index('ix_historical_metrics_name_time', table_name='analytics_historical_metrics')
    op.drop_table('analytics_historical_metrics')
    op.drop_table('analytics_daily_statistics')
    # ### end Alembic commands ###
