"""add_validation_models

Revision ID: b2becf4bc7fd
Revises: 203f39413e09
Create Date: 2026-07-24 20:03:09.367008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2becf4bc7fd'
down_revision: Union[str, Sequence[str], None] = '203f39413e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('extraction_run_id', sa.UUID(), nullable=False),
    sa.Column('validator_name', sa.String(), nullable=False),
    sa.Column('validator_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('artifact_storage_key', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('validated_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('validation_run_id', sa.UUID(), nullable=False),
    sa.Column('extracted_field_id', sa.UUID(), nullable=False),
    sa.Column('validation_status', sa.Enum('SUPPORTED', 'PARTIALLY_SUPPORTED', 'UNSUPPORTED', 'MISSING_EVIDENCE', 'AMBIGUOUS', name='validationstatus'), nullable=False),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('validation_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extracted_field_id'], ['extracted_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('validated_field_id', sa.UUID(), nullable=False),
    sa.Column('ocr_region_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('support_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ocr_region_id'], ['ocr_regions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validated_field_id'], ['validated_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_evidence')
    op.drop_table('validated_fields')
    op.drop_table('validation_runs')
    # ### end Alembic commands ###
