"""Add classification model

Revision ID: be65e84efa81
Revises: 50cbdf71ecd3
Create Date: 2026-07-23 20:58:59.343888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be65e84efa81'
down_revision: Union[str, Sequence[str], None] = '50cbdf71ecd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_classifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('classifier_name', sa.String(length=100), nullable=False),
    sa.Column('classifier_version', sa.String(length=50), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('artifact_storage_key', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', name='uq_classification_document')
    )
    op.create_index(op.f('ix_document_classifications_document_id'), 'document_classifications', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_classifications_organization_id'), 'document_classifications', ['organization_id'], unique=False)
    # SQLite doesn't support ALTER COLUMN TYPE for enums without batch alter table.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN TYPE for enums without batch alter table.
    pass
    op.drop_index(op.f('ix_document_classifications_organization_id'), table_name='document_classifications')
    op.drop_index(op.f('ix_document_classifications_document_id'), table_name='document_classifications')
    op.drop_table('document_classifications')
    # ### end Alembic commands ###
