"""add_phase9_review_models

Revision ID: ec53a9403aac
Revises: 06a3ae7fecf6
Create Date: 2026-07-24 21:02:32.583918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec53a9403aac'
down_revision: Union[str, Sequence[str], None] = '06a3ae7fecf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'IN_REVIEW', 'APPROVED', 'PARTIALLY_APPROVED', 'REJECTED', 'AUTO_APPROVED', name='reviewstatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index(op.f('ix_review_sessions_assigned_user_id'), 'review_sessions', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_review_sessions_organization_id'), 'review_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_review_sessions_status'), 'review_sessions', ['status'], unique=False)
    op.create_table('review_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_session_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_session_id', sa.UUID(), nullable=False),
    sa.Column('validated_field_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validated_field_id'], ['validated_fields.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_session_id', sa.UUID(), nullable=False),
    sa.Column('validated_field_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVE', 'REJECT', 'CORRECT', name='reviewdecisiontype'), nullable=False),
    sa.Column('corrected_value', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_session_id'], ['review_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validated_field_id'], ['validated_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_decisions')
    op.drop_table('review_comments')
    op.drop_table('review_histories')
    op.drop_index(op.f('ix_review_sessions_status'), table_name='review_sessions')
    op.drop_index(op.f('ix_review_sessions_organization_id'), table_name='review_sessions')
    op.drop_index(op.f('ix_review_sessions_assigned_user_id'), table_name='review_sessions')
    op.drop_table('review_sessions')
    # ### end Alembic commands ###
