"""phase12_security

Revision ID: fffaaad336f9
Revises: 16ccd25ae4b8
Create Date: 2026-07-25 10:16:11.069799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fffaaad336f9'
down_revision: Union[str, Sequence[str], None] = '16ccd25ae4b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('documents', 'status',
#                existing_type=sa.VARCHAR(length=10),
#                type_=sa.Enum('REGISTERED', 'UPLOADED', 'CONVERTING', 'CONVERTED', 'CONVERSION_FAILED', 'PROCESSING', 'PROCESSED', 'FAILED', 'ARCHIVED', 'OCR_PROCESSING', 'OCR_COMPLETED', 'OCR_PARTIAL', 'OCR_FAILED', 'CLASSIFICATION_PROCESSING', 'CLASSIFIED', 'CLASSIFICATION_FAILED', 'EXTRACTION_PROCESSING', 'EXTRACTED', 'EXTRACTION_FAILED', 'VALIDATION_PROCESSING', 'VALIDATED', 'VALIDATION_FAILED', 'REVIEW_PENDING', 'UNDER_REVIEW', 'REVIEW_COMPLETED', 'FINALIZED', 'AUTO_APPROVED', name='documentstatus'),
#                existing_nullable=False)
#     op.alter_column('memberships', 'role',
#                existing_type=sa.VARCHAR(length=8),
#                type_=sa.Enum('SYSTEM_ADMIN', 'OWNER', 'ADMIN', 'REVIEWER', 'OPERATOR', 'VIEWER', 'API_CLIENT', name='membershiprole'),
#                existing_nullable=False)
#     op.alter_column('pages', 'status',
#                existing_type=sa.VARCHAR(length=10),
#                type_=sa.Enum('PENDING', 'MATERIALIZED', 'PROCESSING', 'PROCESSED', 'FAILED', 'OCR_PROCESSING', 'OCR_COMPLETED', 'OCR_FAILED', name='pagestatus'),
#                existing_nullable=False)
#     op.alter_column('review_comments', 'id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('review_comments', 'review_session_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('review_comments', 'validated_field_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
#     op.alter_column('review_comments', 'reviewer_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('review_decisions', 'id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('review_decisions', 'review_session_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('review_decisions', 'validated_field_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('review_decisions', 'reviewer_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('review_histories', 'id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('review_histories', 'review_session_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('review_sessions', 'id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('review_sessions', 'organization_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('review_sessions', 'document_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('review_sessions', 'assigned_user_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=True)
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_system_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
#     op.alter_column('validated_fields', 'id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('validated_fields', 'validation_run_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('validated_fields', 'extracted_field_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('validation_evidence', 'id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('validation_evidence', 'validated_field_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('validation_evidence', 'ocr_region_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('validation_evidence', 'page_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('validation_runs', 'id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('validation_runs', 'organization_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('validation_runs', 'document_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
#     op.alter_column('validation_runs', 'extraction_run_id',
#                existing_type=sa.NUMERIC(),
#                type_=sa.UUID(),
#                existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('validation_runs', 'extraction_run_id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('validation_runs', 'document_id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('validation_runs', 'organization_id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('validation_runs', 'id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('validation_evidence', 'page_id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('validation_evidence', 'ocr_region_id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('validation_evidence', 'validated_field_id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('validation_evidence', 'id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('validated_fields', 'extracted_field_id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('validated_fields', 'validation_run_id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('validated_fields', 'id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'is_system_admin')
    op.drop_column('users', 'hashed_password')
#     op.alter_column('review_sessions', 'assigned_user_id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=True)
#     op.alter_column('review_sessions', 'document_id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('review_sessions', 'organization_id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('review_sessions', 'id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('review_histories', 'review_session_id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('review_histories', 'id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('review_decisions', 'reviewer_id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('review_decisions', 'validated_field_id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('review_decisions', 'review_session_id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('review_decisions', 'id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('review_comments', 'reviewer_id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('review_comments', 'validated_field_id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=True)
#     op.alter_column('review_comments', 'review_session_id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('review_comments', 'id',
#                existing_type=sa.UUID(),
#                type_=sa.NUMERIC(),
#                existing_nullable=False)
#     op.alter_column('pages', 'status',
#                existing_type=sa.Enum('PENDING', 'MATERIALIZED', 'PROCESSING', 'PROCESSED', 'FAILED', 'OCR_PROCESSING', 'OCR_COMPLETED', 'OCR_FAILED', name='pagestatus'),
#                type_=sa.VARCHAR(length=10),
#                existing_nullable=False)
#     op.alter_column('memberships', 'role',
#                existing_type=sa.Enum('SYSTEM_ADMIN', 'OWNER', 'ADMIN', 'REVIEWER', 'OPERATOR', 'VIEWER', 'API_CLIENT', name='membershiprole'),
#                type_=sa.VARCHAR(length=8),
#                existing_nullable=False)
#     op.alter_column('documents', 'status',
#                existing_type=sa.Enum('REGISTERED', 'UPLOADED', 'CONVERTING', 'CONVERTED', 'CONVERSION_FAILED', 'PROCESSING', 'PROCESSED', 'FAILED', 'ARCHIVED', 'OCR_PROCESSING', 'OCR_COMPLETED', 'OCR_PARTIAL', 'OCR_FAILED', 'CLASSIFICATION_PROCESSING', 'CLASSIFIED', 'CLASSIFICATION_FAILED', 'EXTRACTION_PROCESSING', 'EXTRACTED', 'EXTRACTION_FAILED', 'VALIDATION_PROCESSING', 'VALIDATED', 'VALIDATION_FAILED', 'REVIEW_PENDING', 'UNDER_REVIEW', 'REVIEW_COMPLETED', 'FINALIZED', 'AUTO_APPROVED', name='documentstatus'),
#                type_=sa.VARCHAR(length=10),
#                existing_nullable=False)
    # ### end Alembic commands ###
